# Generated by Django 5.0.1 on 2024-01-18 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('device', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('took_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device')),
                ('user', models.ForeignKey(on_delete=models.SET('User removed'), to='accounts.customuser')),
            ],
        ),
    ]
