# Generated by Django 5.0.1 on 2024-01-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignlog',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
