#GET http://127.0.0.1:8000/device/custom/  # Replace with your actual endpoint

POST http://127.0.0.1:8000/device/

Content-Type: application/json

{
    "brand":"Samsung",
    "model_name":"galaxy s20",
    "IMEI_number":"IED4561FGFHGF15",
    "status":"available"
}