databases:
- name: device_tracker_2
  databaseName: device_tracker_2
  user: device_tracker_2_user

services:
  - type: web
    name: device-tracker
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DB_URL
        fromDatabase:
        name: device-tracker
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
