# Generated by Django 5.0.1 on 2024-01-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('slack_id', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, choices=[('tester', 'Tester'), ('developer', 'Developer'), ('admin', 'Admin')], max_length=100, null=True)),
                ('picture_url', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
