# Generated by Django 5.0.1 on 2024-01-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('tester', 'Tester'), ('developer', 'Developer'), ('admin', 'Admin')], max_length=100, null=True),
        ),
    ]
